Homework 1 swift
pingvin1977/ios-school-homeworks pull request #2
Opened 2020-09-03 16:54 UTC by pingvin1977

2020-09-04 13:48 UTC, dersim-davaod requested changes
This is the first bunch of comments related to readability. Please consider improvements.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/.gitignore
> +.DS_Store
You don't have to create a new .gitignore file. You can update the existing file at `/.gitignore` path.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func arithmeticsFunction(array: [Int]) -> (arithmetic: Double, mediana: Double, moda: Set<Int>) {
From function's name I don't understand its purpose.
What does that mean `arithmeticsFunction`? Which function?

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func arithmeticsFunction(array: [Int]) -> (arithmetic: Double, mediana: Double, moda: Set<Int>) {
Please use English notions. For example, not `mediana`, but `median`.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func arithmeticsFunction(array: [Int]) -> (arithmetic: Double, mediana: Double, moda: Set<Int>) {
Each function should be a separate one.

Let's imagine you want to remove the calculation of median. To do this you have to change the signature of the function (API), the function itself and the value it returns. That's too many side effects for simple removing.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    //var setOfNumbers = Set<Int>(array)
Remove commented/useless code.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var sumOfNumbers = 0
Do you need to put initial `0` value here?

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var medianaNumber: Double
Use more straight and simple naming: for example, `median` instead of `medianaNumber`. Everyone knows that median is a number. Please revise the rest of variables.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    for numberOfArray in array {
```suggestion
    for number in array {
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func arithmeticsFunction(array: [Int]) -> (arithmetic: Double, mediana: Double, moda: Set<Int>) {
`array` is a bad name. I know it's array. For me it's more important to know the semantics.

```suggestion
func arithmeticsFunction(numbers: [Int]) -> (arithmetic: Double, mediana: Double, moda: Set<Int>) {
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    arithmeticNumber = Double(sumOfNumbers)/Double(array.count)
```suggestion
    arithmeticNumber = Double(sumOfNumbers) / Double(array.count)
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var arithmeticNumber: Double
```suggestion
    var arithmeticMean: Double
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    // calculated mean
If you believe you need to write a comment, that's a sign you might want to extract the code into a function, typically.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +       let prewiousNumberOfArray = arraySortedOfNumbers.count / 2 - 1
A typo:
```suggestion
       let previousNumberOfArray = arraySortedOfNumbers.count / 2 - 1
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +       let prewiousNumberOfArray = arraySortedOfNumbers.count / 2 - 1
What does that mean "previous number of array"? Which previous?

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +       let nextNumberOfArray = arraySortedOfNumbers.count / 2
What does that mean "next number"? Next after what?
It's hard to read the logic with such naming.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var previousItem = 0  //optional
What does that mean - optional? Why the comment is here?

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var entersOfNumber = [Int: Int]()
```suggestion
    var count = [Int: Int]()
```
or
```suggestion
    var counter = [Int: Int]()
```
?

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var numberOfItem = 0
which item?

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    for numberOfSortedArray in arraySortedOfNumbers {
```suggestion
    for number in arraySortedOfNumbers {
```

I see that we're iterating the `arraySortedOfNumbers`.

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    let sortedEntersOfNumbers = entersOfNumber.sorted{ return $0.value>$1.value}
```suggestion
    let sortedEntersOfNumbers = entersOfNumber.sorted{ return $0.value > $1.value}
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +
```suggestion
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    for (number, quantity) in sortedEntersOfNumbers {
```suggestion
    previousItem = 1
    
    for (number, quantity) in sortedEntersOfNumbers {
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +let arrayNumber = [1,1,1,1,1,3,3,3,3,3]
Please separate the implementation and the test code, at least visually (you can insert 2 blank lines).

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +//let arrayNumber = [0]
What is that?

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +let mean = arithmeticsFunction(array: arrayNumber).arithmetic
I don't like the API.
How I should know which statistics are available in `arithmeticsFunction`?

I prefer to see the following signature instead:
```swift
median(numbers: [Int]) -> Int
```

2020-09-04 13:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +let mean = arithmeticsFunction(array: arrayNumber).arithmetic
And then use it like:
```swift
let median = median([0, 1, 2])
```

2020-09-04 14:32 UTC, pingvin1977 commented on MyPlayground.playground/.gitignore
> +.DS_Store
ok.

2020-09-04 14:37 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func arithmeticsFunction(array: [Int]) -> (arithmetic: Double, mediana: Double, moda: Set<Int>) {
This is a general function for mediana, moda and mean. Rename to be understood.

2020-09-04 14:38 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func arithmeticsFunction(array: [Int]) -> (arithmetic: Double, mediana: Double, moda: Set<Int>) {
ok.

2020-09-04 18:08 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    //var setOfNumbers = Set<Int>(array)
Remove all commented/useless code

2020-09-04 18:12 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var sumOfNumbers = 0
If not assign a value 0 cannot be assigned a value sumOfNumbers += elementOfNumber

2020-09-04 18:13 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var medianaNumber: Double
Fixed.

2020-09-04 18:13 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    for numberOfArray in array {
Fixed.

2020-09-04 18:14 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func arithmeticsFunction(array: [Int]) -> (arithmetic: Double, mediana: Double, moda: Set<Int>) {
Fixed.

2020-09-04 18:15 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    arithmeticNumber = Double(sumOfNumbers)/Double(array.count)
Fixed.

2020-09-04 18:15 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var arithmeticNumber: Double
Fixed.

2020-09-04 18:15 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    // calculated mean
Ok.

2020-09-04 18:17 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var previousItem = 0  //optional
Fixed.

2020-09-04 18:17 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var entersOfNumber = [Int: Int]()
Fixed.

2020-09-04 18:18 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    for (number, quantity) in sortedEntersOfNumbers {
Fixed.

2020-09-04 18:25 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +
Fixed.

2020-09-04 18:25 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +//let arrayNumber = [0]
Fixed.

2020-09-04 18:39 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +let arrayNumber = [1,1,1,1,1,3,3,3,3,3]
Fixed.

2020-09-04 18:42 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +       let prewiousNumberOfArray = arraySortedOfNumbers.count / 2 - 1
Corrected to lowerBoundOfInterval and upperBoundOfInterval.

2020-09-04 18:44 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +       let nextNumberOfArray = arraySortedOfNumbers.count / 2
Fixed.

2020-09-04 18:52 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var numberOfItem = 0
Value quantity. Corrected by valueOfItem.

2020-09-04 18:52 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    for numberOfSortedArray in arraySortedOfNumbers {
Fixed.

2020-09-04 18:53 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    let sortedEntersOfNumbers = entersOfNumber.sorted{ return $0.value>$1.value}
Fixed.

2020-09-07 09:38 UTC, dersim-davaod commented on MyPlayground.playground/.gitignore
> +.DS_Store
I still see the same file.

2020-09-07 10:09 UTC, pingvin1977 commented on MyPlayground.playground/.gitignore
> +.DS_Store
Fixed. File deleted.

2020-09-07 10:44 UTC, dersim-davaod requested changes

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func Median(numbers: [Int]) -> Double {
The current implementation returns `1` as median for input `[1,2,3]`. That's wrong.

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func Moda(numbers: [Int]) -> Set<Int> {
```suggestion
func moda(numbers: [Int]) -> Set<Int> {
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func Moda(numbers: [Int]) -> Set<Int> {
Also check spelling please:

```suggestion
func Mode(numbers: [Int]) -> Set<Int> {
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var moda = Set<Int>()
```suggestion
    var mode = Set<Int>()
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var moda = Set<Int>()
Also the set can contain more than one mode, so it makes sense to name var as `modes`:
```suggestion
    var modes = Set<Int>()
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    let numbersSorted = numbers.sorted()
```suggestion
    let sortedNumbers = numbers.sorted()
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    for ItemOfNumber in numbersSorted {
Capitalized letters:
```suggestion
    for itemOfNumber in numbersSorted {
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var count = [Int: Int]()
one more nit:
it's better to name it `counter` as it's counter.

```suggestion
    var counter = [Int: Int]()
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    let countSorted = count.sorted{ return $0.value > $1.value}
```suggestion
    let countSorted = count.sorted { return $0.value > $1.value }
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    let countSorted = count.sorted{ return $0.value > $1.value}
```suggestion
    let sortedCounters = count.sorted{ return $0.value > $1.value}
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    return moda
I would prefer to get a sorted sequence of numbers from the function.

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +let arrayNumber = [1,2,2,2,3,3,6]
I know it's an array.

```suggestion
let numbers = [1,2,2,2,3,3,6]
```
or
```suggestion
let testNumbers = [1,2,2,2,3,3,6]
```
or
```suggestion
let input = [1,2,2,2,3,3,6]
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +print("Mean: \(Mean(numbers: arrayNumber))")
In some cases it's better to see the following code:
```swift
print("Mean: \(mean(testNumbers))")
```

instead of:
```swift
print("Mean: \(mean(numbers: testNumbers))")
```

Could you please update the implementation to have such API?

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +print("Moda: \(Moda(numbers: arrayNumber))")
```suggestion
print("Mode: \(Moda(numbers: arrayNumber))")
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +        if previousItem > quantity {
It's hard to understand what's going on here.
Why we compare an item with some quantity?

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +        }
If you have to do something in both branch you shouldn't duplicate the code (remember DRY principle):

```suggestion
        if ItemOfNumber == previousItem {
            valueOfItem += 1
            count[previousItem] = valueOfItem
        } else {
            valueOfItem = 1
            count[ItemOfNumber] = valueOfItem
        }
        previousItem = ItemOfNumber
```

2020-09-07 10:44 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    for ItemOfNumber in numbersSorted {
Moreover:
```suggestion
    for number in numbersSorted {
```

First, be simple.
Second, How you can translate "item of number" into Russian?

2020-09-07 10:54 UTC, dersim-davaod commented on MyPlayground.playground/.gitignore
> +.DS_Store
And where are the changes related to `.DS_Store` files?

2020-09-07 11:29 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    for elementOfNumber in numbers {
Fixed.

2020-09-07 11:30 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func Mean(numbers: [Int]) -> Double {
Fixed.

2020-09-07 11:30 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func Median(numbers: [Int]) -> Double {
FIxed.

2020-09-07 11:33 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    let numbersSorted = numbers.sorted()
Fixed.

2020-09-07 11:42 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    if numbersSorted.count % 2 == 0 {
Fixed.

2020-09-07 11:42 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        let median = (Double(numbersSorted[lowerBoundOfInterval]) + Double(numbersSorted[upperBoundOfInterval])) / 2
Fixed.

2020-09-07 11:43 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func Moda(numbers: [Int]) -> Set<Int> {
Fixed.

2020-09-07 11:44 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var moda = Set<Int>()
FIxed.

2020-09-07 11:44 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    let numbersSorted = numbers.sorted()
Fixed.

2020-09-07 11:47 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var count = [Int: Int]()
Fixed.

2020-09-07 11:48 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    let countSorted = count.sorted{ return $0.value > $1.value}
Fixed.

2020-09-07 11:54 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    let countSorted = count.sorted{ return $0.value > $1.value}
Fixed.

2020-09-07 11:56 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +let arrayNumber = [1,2,2,2,3,3,6]
Corrected to testNumbers.

2020-09-07 11:56 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +print("Moda: \(Moda(numbers: arrayNumber))")
Fixed.

2020-09-07 11:57 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        }
Fixed.

2020-09-07 12:02 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +
Fixed.

2020-09-07 12:16 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func Median(numbers: [Int]) -> Double {
Fixed.

2020-09-07 12:23 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    for ItemOfNumber in numbersSorted {
itemOfNumbers - значение номера. Corrected to number.

2020-09-07 12:52 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    return moda
Fixed.

2020-09-07 13:23 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +print("Mean: \(Mean(numbers: arrayNumber))")
Updated API.

2020-09-07 13:53 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        let lowerBoundOfInterval = numbersSorted.count / 2 - 1
The half-sum of the numbers in the middle places in the ordered set of these numbers (if their number is even).
lowerBoundOfInterval - left spacing value, upperBoundOfInterval - right spacing value.
Lower bound of interval is not 0, this is number of left spacing value in array.

2020-09-07 13:57 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        let upperBoundOfInterval = numbersSorted.count / 2
No. There are 6 elements in the array. count = 6. Upper bound of interval is 3.

2020-09-07 20:18 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    if numbers.isEmpty { return 0 }
Fixed.

2020-09-07 20:19 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    if numbers.isEmpty { return 0 }
Fixed.

2020-09-07 20:20 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    for ItemOfNumber in numbersSorted {
Fixed.

2020-09-08 08:45 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        let lowerBoundOfInterval = numbersSorted.count / 2 - 1
Fixed.

2020-09-08 08:45 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        let upperBoundOfInterval = numbersSorted.count / 2
Fixed.

2020-09-08 09:38 UTC, pingvin1977 commented on MyPlayground.playground/.gitignore
> +.DS_Store
Fixed .gitignore.

2020-09-08 09:39 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        if previousItem > quantity {
Fixed.

2020-09-08 16:48 UTC, dersim-davaod requested changes
Consider some improvements:

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func mean(_ numbers: [Int]) -> Double? {
the result value for the input `[1,2,3,4]` is wrong.

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +      }  else  {
Please align
```swift
if {
} else {
}
```
block properly.

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +      }  else  {
```suggestion
      } else {
```

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +func modes(_ numbers: [Int]) -> [Int]? {
You don't need to have an optional result value. If you do not have modes, you just return empty array.

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +            valueOfItem += 1
Looks like you don't need a `valueOfItem`. Could you please try to rewrite the code to avoid using this variable?

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +if mean(testNumbers) != nil {
Try to use `if let` syntax here and below.

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    print("Mode: \(modes(testNumbers)!)")
```suggestion
    print("Modes: \(modes(testNumbers)!)")
```

here and below.

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    var valueOfItem = 0
nit:
"value of item" - which item?

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +
```suggestion
```

2020-09-08 16:48 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +        if number == previousValue {
The code works correct, but let's think about it:

on the first iteration at
```swift
for number in sortedNumbers
```
loop, there's no `previousValue` (you think it's zero, but in fact it doesn't exist).

So it's a bit confusing, I'd recommend to improve the implementation here.

2020-09-08 16:48 UTC, dersim-davaod commented on .gitignore
> +.DS_Store≈
Please check if the current version of .gitignore works.

2020-09-08 16:54 UTC, pingvin1977 commented on .gitignore
> +.DS_Store≈
Fixed.

2020-09-08 16:56 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +
Fixed.

2020-09-08 17:01 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +      }  else  {
Fixed.

2020-09-08 17:01 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +      }  else  {
Fixed.

2020-09-08 17:02 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    print("Mode: \(modes(testNumbers)!)")
Fixed.

2020-09-08 20:32 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func mean(_ numbers: [Int]) -> Double? {
Fixed.

2020-09-08 20:35 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +func modes(_ numbers: [Int]) -> [Int]? {
Fixed.

2020-09-08 20:59 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +if mean(testNumbers) != nil {
Fixed.

2020-09-08 21:00 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +
Fixed.

2020-09-09 11:33 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +            valueOfItem += 1
Fixed.

2020-09-09 11:33 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    var valueOfItem = 0
Fixed.

2020-09-09 11:34 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        if number == previousValue {
Fixed.

2020-09-10 15:54 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +  }
```suggestion
}
```

2020-09-10 15:54 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +if mean(testNumbers) != nil {
I still recommend to use `if let` syntax:
```swift
if let median = median(testNumbers) {
    print("Median: \(median)")
}
```

2020-09-10 15:59 UTC, dersim-davaod requested changes
Some improvements:

2020-09-10 15:59 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +let valueMean = mean(testNumbers)
Be simple:

```suggestion
let mean = mean(testNumbers)
```

2020-09-10 15:59 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +        if previousValue > value {
The comment is related to the [previous review](https://github.com/pingvin1977/ios-school-homeworks/pull/2#discussion_r485060806):

You said it is fixed.
Could you please explain what's the fix?

I still didn't understand why there's a comparison with `previousValue` even there's no previous value on the first iteration.

2020-09-10 18:22 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +let valueMean = mean(testNumbers)
Fixed.

2020-09-10 18:23 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +  }
Fixed.

2020-09-10 18:26 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        if previousValue > value {
Corrected 
```
  var maxValue = 1

    for (key, value) in sortedCounters {
        if maxValue > value {
            break
        } else {
            modes.insert(key)
            maxValue = value
        }
    }
```

2020-09-10 18:30 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +if mean(testNumbers) != nil {
Fixed.

2020-09-11 14:47 UTC, dersim-davaod reviewed
Almost done. Just additional improvement in the implementation:

2020-09-11 14:47 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    }
I would recommend to rewrite this piece of code to make it readable and faster.
Try to count occurrences without sorting the initial list of numbers. The idea behind is to take a look at the list of numbers and just count occurrences.

Does that make sense?

2020-09-11 19:05 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    }
Rewrite of code.

2020-09-12 06:28 UTC, dersim-davaod requested changes

2020-09-12 06:28 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    for ( _ , value) in numbers.enumerated() {
As you use the value only, you don't have to use `enumerated`. It is enough to iterate the array:
```swift
for number in numbers
```

2020-09-12 06:28 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +        }
The code is good, basically.

1. Try to avoid force unwrapping. That's a point where a lot of issues come.

2. You can simplify the code.

Try to get rid of `if` block and use the `defaultValue` parameter from [subscript(_:default:)](https://developer.apple.com/documentation/swift/dictionary/2894528-subscript) method.

2020-09-12 06:28 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    print("Mean: not value")
nit:
You can be more friendly to the user:
```suggestion
    print("There is no mean value in empty array.")
```

2020-09-12 06:28 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +if  !valueModes.isEmpty {
```suggestion
if !valueModes.isEmpty {
```

2020-09-12 06:28 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +
nit:

That's not an issue, but let's agree to remove blank lines in the beginning/in the end of the function's body:

```suggestion
```

Once again: that's not an issue, the main goal here is to be consistent (what you do).

But that would be more convenient for me :)

Can we have such agreement please?

2020-09-12 06:28 UTC, dersim-davaod commented on .gitignore
> +.DS_Store
That's not related to Xcode's user settings.

Please put this line in the separate block and comment it properly. For example:

```
# macOS environment
.DS_Store

```

2020-09-12 06:55 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +
Fixed.

2020-09-12 06:55 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +if  !valueModes.isEmpty {
Fixed.

2020-09-12 06:58 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    print("Mean: not value")
Fixed.

2020-09-12 09:46 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    for ( _ , value) in numbers.enumerated() {
Fixed.

2020-09-12 17:05 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +        }
Fixed.

2020-09-12 17:13 UTC, pingvin1977 commented on .gitignore
> +.DS_Store
Fixed.

2020-09-13 06:32 UTC, dersim-davaod requested changes
Great job! Just a couple more nits:

2020-09-13 06:32 UTC, dersim-davaod commented on .gitignore
> +# macOS environment
nit, but:

Please see comments get you hierarchy:
```
# section
## subsection
## subsection
...
## subsection
```

With your changes you break the hierarchy for Xcode. It makes sense to include the changes in the beginning of the file instead.

Does that make sense?

2020-09-13 06:32 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +
Remove blank line, please as discussed.

2020-09-13 06:32 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +    print("There is no modes value in empty array.")
Typo (due to plural):

```suggestion
    print("There is no mode values in empty array.")
```

or

```suggestion
    print("There is no modes in empty array.")
```

2020-09-13 08:00 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +    print("There is no modes value in empty array.")
Fixed.

2020-09-13 08:01 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +
Fixed.

2020-09-13 08:13 UTC, pingvin1977 commented on .gitignore
> +# macOS environment
Moved the changes to the beginning of the file.

2020-09-13 08:51 UTC, dersim-davaod requested changes
Please see comments above.

2020-09-13 08:51 UTC, dersim-davaod commented on MyPlayground.playground/Contents.swift
> +
No, it wasn't fixed.

2020-09-13 09:21 UTC, pingvin1977 commented on MyPlayground.playground/Contents.swift
> +
Sorry removed in the wrong place. Fixed.

2020-09-13 09:27 UTC, dersim-davaod approved these changes
Great job! Well done 💪

2020-09-14 21:42 UTC, merged