First download. This is a working version
pingvin1977/ios-school-homeworks pull request #3
Opened 2020-09-21 20:21 UTC by pingvin1977

2020-09-22 07:58 UTC, dersim-davaod requested changes

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    func push (_ element: Int) {
```suggestion
    func push(_ element: Int) {
```

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    var stack = [Int]()
In fact, this is not a stack. This is underlying storage.
I'd name it as `storage` or `elements` or `stackElements`.

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    func pop () -> Int? {
```suggestion
    func pop() -> Int? {
```

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +        return stack.removeLast()
Please read the documentation about Array's `popLast()` method.

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +
```suggestion
```

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    func top () -> Int? {
```suggestion
    func top() -> Int? {
```

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    func minimumElement () -> Int? {
```suggestion
    func minimumElement() -> Int? {
```

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    func minimumElement () -> Int? {
Prove the `minimumElement()` method works in O(1).

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +//stack.stack = [1,3,7,4]
What is that?

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +stack.stack
I should have only the interface described in the task (push/pop/top methods).

Imagine you can have the following code in the current file:

```swift
let s = Stack()
s.stack.append(10)
```

There's an issue with encapsulation.
1) Can you see it? If yes, please describe it.
2) Could you please try to improve the implementation?

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +stackStatistic.stack = [3,7,9,2,1,9]
See comment about encapsulation violation.

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +stack.push( 3 )
```suggestion
stack.push(3)
```

2020-09-22 07:58 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +            let value = super.pop()!
Force unwrapping is a bad practice, typically. 
Try to avoid it, otherwise you can have an accidental crash somewhen.

2020-09-22 08:06 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    func push (_ element: Int) {
Fixed.

2020-09-22 08:09 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    var stack = [Int]()
Renamed the stack to stackElement

2020-09-22 08:09 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    func pop () -> Int? {
Fixed.

2020-09-22 08:09 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +
Fixed.

2020-09-22 08:10 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +stack.push( 3 )
Fixed.

2020-09-22 11:55 UTC, dersim-davaod commented
I don't like the name of the current PR. Please adjust it.

2020-09-22 11:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    var stack = [Int]()
`stackElement` means it contains one element from stack.
You're going to store 0+ elements, thus the name should be `stackElements`.
Please fix it.

2020-09-23 10:23 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +            let value = super.pop()!
Fixed.

2020-09-23 10:24 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +//stack.stack = [1,3,7,4]
Deleted comment.

2020-09-23 10:25 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    func minimumElement () -> Int? {
Fixed function minimumElement().

2020-09-23 10:25 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    func minimumElement () -> Int? {
Fixed.

2020-09-23 10:25 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    func top () -> Int? {
Fixed.

2020-09-23 10:26 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +        return stack.removeLast()
removeLast() fixed on popLast().

2020-09-23 10:27 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    var stack = [Int]()
Renamed the stack stackElement to stackElements.

2020-09-23 10:32 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +stack.stack
Fixed interface in StackStatistics().

2020-09-23 10:32 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +stackStatistic.stack = [3,7,9,2,1,9]
Fixed.

2020-09-23 11:27 UTC, dersim-davaod requested changes
Please read the comment above about PR's name.

2020-09-23 18:09 UTC, dersim-davaod requested changes

2020-09-23 18:09 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +        if minValuesOfStack.isEmpty || element < minValuesOfStack.last! {
See [my comment](https://github.com/pingvin1977/ios-school-homeworks/pull/3#discussion_r492541749) about force unwrapping. I still recommend to avoid it. Basically, you can rewrite and simplify the method `push(_ element:)`

2020-09-24 18:58 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +        if minValuesOfStack.isEmpty || element < minValuesOfStack.last! {
Fixed.

2020-09-25 07:14 UTC, dersim-davaod requested changes
Code works fine 👍 
Now polish the rest.

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Complexity: O(1)
nit: no issue here, just another reminder on what we have discussed sometimes it's easier to write the doc with multiline doc comment. Just don't be shy to use it:
```suggestion
    /**
     Adds an element the top of the stack.

     - Parameter element: The number `Int` to add at the top of the stack
     - Complexity: O(1)
     */
```

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Adds an element the top of the stack.
```suggestion
    /// Adds an element on the top of the stack.
```

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Parameter element: The number `Int` to add at the top of the stack
I know parameter is `Int`. I see it from function's signature.

```suggestion
    /// - Parameter element: An element to add on the top of the stack
```

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Parameter element: The number `Int` to add at the top of the stack
If you have decided to have dot signs (`.`) then use it consistently:
```suggestion
    /// - Parameter element: The number `Int` to add at the top of the stack.
```

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    ///  - Returns: The pop element of the stack if the stack is not
What is `The pop element`?

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Adds an element the top of the stack.
What is top of the stack? Imagine, you didn't work with the stack. Do you understand what that mean?

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Adds an element the top of the stack.
Here and below.

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    private var currentMinElements = [Int]()
Where's the documentation?

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Returns: The pop element of the stack if the stack is not
1. What is a "pop element"?
2. Does this method returns "pop element"?

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +# StackStatistic
Have you read articles about the README file?

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +# StackStatistic
```suggestion
# StackStatistics
```

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +StackStatistic is a class for work with elements of stack.
```suggestion
StackStatistics is a class for work with elements of stack.
```

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +StackStatistic is a class for work with elements of stack.
As we have discussed, I don't like the description of the class. It's useless.

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +var stackStatistic = StackStatistics()
Next time before submitting the changes, check it for minor typos.

```suggestion
var stackStatistics = StackStatistics()
```

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +var stackStatistic = StackStatistics()
even better:
```suggestion
var stack = StackStatistics()
```

This is because I know the type of the stack.
You don't name `Int` variable as `ageInt`, don't you?

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
Use ` ```swift``` ` markdown syntax to format the code (review the corresponding documentation).

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
What is that? Is that still "Usage"?

2020-09-25 07:14 UTC, dersim-davaod commented on README.md
> +
Please remove excess blank lines.

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +// MARK: - Stack
Add blank line around `// MARK: -`s

```suggestion
// MARK: - Stack

```

2020-09-25 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +// MARK: - Stack
Please double check the rest.

2020-09-25 09:18 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +/// Standard functions for working with the stack.
Fixed.

2020-09-25 09:22 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Complexity: O(1)
Fixed.

2020-09-25 09:24 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Adds an element the top of the stack.
Sorry for my English. Fixed.

2020-09-25 09:26 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Parameter element: The number `Int` to add at the top of the stack
Fixed.

2020-09-25 09:26 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Parameter element: The number `Int` to add at the top of the stack
Fixed.

2020-09-25 09:27 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Complexity: O(1)
Again, this is not an issue. You can stick to any of options. Just be consistent.

2020-09-25 09:36 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    ///  - Returns: The pop element of the stack if the stack is not
Fixed.

2020-09-25 09:40 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Returns: The pop element of the stack if the stack is not
Fixed.

2020-09-25 11:14 UTC, pingvin1977 commented on README.md
> +var stackStatistic = StackStatistics()
Fixed

2020-09-25 12:14 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +// MARK: - Stack
Fixed.

2020-09-25 12:38 UTC, pingvin1977 commented on README.md
> +StackStatistic is a class for work with elements of stack.
Fixed.

2020-09-25 12:38 UTC, pingvin1977 commented on README.md
> +# StackStatistic
Fixed.

2020-09-25 13:01 UTC, pingvin1977 commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
Fixed.

2020-09-25 13:02 UTC, pingvin1977 commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
Ok.

2020-09-25 13:02 UTC, pingvin1977 commented on README.md
> +
Fixed.

2020-09-25 13:03 UTC, pingvin1977 commented on README.md
> +StackStatistic is a class for work with elements of stack.
Fixed.

2020-09-25 18:40 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    private var stackElements = [Int]()
Fixed.

2020-09-25 18:43 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    private var currentMinElements = [Int]()
Fixed.

2020-09-25 18:44 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /// - Complexity: O(1)
Ok.

2020-09-26 05:34 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +/// Standard functions for working with the stack.
No, it's not.

2020-09-26 05:34 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    private var stackElements = [Int]()
No, it's not.

2020-09-26 05:41 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     Adds an a top element of the stack data structure organized according to `LIFO` principle.
Why you're repeating this part - `stack data structure organized according to `LIFO` principle` everywhere?

2020-09-26 05:41 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     - Returns: The top element of the stack if the stack is not empty; otherwise, `nil`.
Again - what is the `top element` here? Where's the explanation of what is a `top`?

2020-09-26 05:41 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    private var currentMinElements = [Int]()
Still can't see documentation.

2020-09-26 05:41 UTC, dersim-davaod commented on README.md
> +StackStatistics is a class for work with elements of stack.
Still see useless description of the repo/classes.

2020-09-26 05:41 UTC, dersim-davaod commented on README.md
> +# StackStatistics
And please answer my question that you ignored: have you read articles about the README file?

2020-09-26 05:41 UTC, dersim-davaod commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
What was fixed?

2020-09-26 05:52 UTC, dersim-davaod requested changes
1. Before re-requesting review, make sure you addressed all comments. Currently I see comments that were answered, but I couldn't see corresponding changes in the change list.
1. Please put more efforts to provide clear and useful documentation.
1. Please review a previous bunch of comments that are not resolved.

2020-09-26 05:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +/// Provides getting the minimum element for stack data structure organized according to `LIFO` principle.
Does the class provides only "getting minimum element" operation for stack?

2020-09-26 05:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    */
Please use standard indentation.

When writing a multiline doc comment, enter characters: `/`, `*`, `*`. After that the autocomplete mechanism will get you remain characters `*`, `/` after the cursor position. Then just hit `Enter` and see where's the default indentation.

Does that make sense?

2020-09-26 05:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    */
Please check the rest.

2020-09-26 05:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +/// Provides standard interface for stack data structure organized according to `LIFO` principle.
Please wrap doc comments at 80th character as max (more details at https://softwareengineering.stackexchange.com/questions/604/is-the-80-character-limit-still-relevant-in-times-of-widescreen-monitors)

```suggestion
/// Provides standard interface for stack data structure
/// organized according to `LIFO` principle.
```

2020-09-26 05:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +/// Provides standard interface for stack data structure organized according to `LIFO` principle.
Otherwise it's not convenient to review long lines:

<img width="544" alt="Screen Shot 2020-09-26 at 08 49 58" src="https://user-images.githubusercontent.com/6073510/94331469-49d47a00-ffd5-11ea-9a6f-7052d8392953.png">

2020-09-27 09:51 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +/// Standard functions for working with the stack.
Fixed.

2020-09-27 09:52 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    private var stackElements = [Int]()
Fixed.

2020-09-27 09:53 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Adds an element the top of the stack.
Fixed.

2020-09-27 09:55 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    private var currentMinElements = [Int]()
Fixed.

2020-09-27 10:00 UTC, pingvin1977 commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
Fixed.

2020-09-27 10:01 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     Adds an a top element of the stack data structure organized according to `LIFO` principle.
Fixed.

2020-09-27 10:02 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     - Returns: The top element of the stack if the stack is not empty; otherwise, `nil`.
Fixed.

2020-09-27 12:28 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +/// Provides standard interface for stack data structure organized according to `LIFO` principle.
Fixed.

2020-09-27 12:28 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    */
Fixed.

2020-09-27 12:28 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +/// Provides getting the minimum element for stack data structure organized according to `LIFO` principle.
Fixed.

2020-09-27 14:03 UTC, pingvin1977 commented on README.md
> +# StackStatistics
I have read articles about the README file. 
Сorrected according to the article.

2020-09-27 14:04 UTC, pingvin1977 commented on README.md
> +StackStatistics is a class for work with elements of stack.
Fixed.

2020-09-27 15:52 UTC, dersim-davaod requested changes

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +## Usage skack operation
```suggestion
## Usage stack operation
```

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> + which are organized according to the principle last in-first out, which is called the <a href="https://en.wikipedia.org/wiki/Stack_(abstract_data_type)">stack</a>.
Please use native markdown syntax for a link (`[link](url)`)

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> + which are organized according to the principle last in-first out, which is called the <a href="https://en.wikipedia.org/wiki/Stack_(abstract_data_type)">stack</a>.
```suggestion
 which are organized according to the principle "last in, first out", which is called the <a href="https://en.wikipedia.org/wiki/Stack_(abstract_data_type)">stack</a>.
```

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +The class StackStatistics is designed to implement API-interfaces for basic operations on a list of elements,
API-interfaces means "Application Programming Interfaces-interfaces". Did you mean that?

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +# Stack Statistics
Is that `StackStatistics` or `Stack Statistics`?

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +# Stack Statistics
I still don't understand what repository contains. I see that class `StackStatistics` is designed to implement API. But what about the repo? Do you remember why we need a README file?

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +The class StackStatistics is designed to implement API-interfaces for basic operations on a list of elements,
You mentioned `StackStatistics`, but also I see `Stack` class in the implementation. Why you didn't mention it in the README?

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +Using the class, it is possible to add an element to the end of the stack, remove the last element,
```suggestion
Using `StackStatistics` class, you can add an element to the end of the stack, remove the last element, 
```

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +Using the class, it is possible to add an element to the end of the stack, remove the last element,
> Using the class, it is possible to add an element **to the end of the stack**, remove the last element 

Where is the "end of the stack"?

> remove the last element

What is the last element?

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +Removes the last element from the stack collection and returns it. If stack collection is empty return 'nil':
This is a `usage` section, not a documentation. Why you're copy-pasting it?

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +Removes the last element from the stack collection and returns it. If stack collection is empty return 'nil':
It should be like:

To add an element to the stack you can use `push(_ element:)` method:
```swift
var stack = StackStatistics()  // creates an empty stack:       []
stack.push(3)                  // stack contains element "3":   [3]
```

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +Return the minimum element in the stack collection. If stack collection is empty return 'nil':
Same concern as above. README is not a dump copy of documentation.

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// An array with the elements of the stack collection.
Be simple:
```suggestion
    /// An array with the elements of the stack.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + which is organized according to the principle last in first out, called a `stack`.
```suggestion
 which is organized according to the principle "last in, first out", called a `stack`.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + which is organized according to the principle last in first out, called a `stack`.
Do you think it's worth to leave the link to `Stack` article at wiki?

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + remove an element from the collection and read the last element of the collection.
Be simple:

```suggestion
 You can add, remove an element from the stack and peek the element that was added last.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + which is organized according to the principle last in first out, called a `stack`.
Do you think it's worth to mention that Stack can hold `Int` values only?

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     Adds the element  to the end of the stack collection.
```suggestion
     Adds the element to the end of the stack.
```

Same below.

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     Adds the element  to the end of the stack collection.
What is "the end of the stack"?

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     func push(_ element: Int) {
Indentation is wrong.
```suggestion
    func push(_ element: Int) {
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     Removes the last element from the stack collection and returns it.
What is "the last element"?

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     Removes the last element from the stack collection and returns it.
```suggestion
     Removes the last element from the stack and returns it.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
```suggestion
     If the stack is empty, return `nil`.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
```suggestion
     If the collection is empty, returns `nil`.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
```suggestion
     If the collection is empty, returns `nil`.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     - Returns: The last element of the collection.
```suggestion
     - Returns: The last element of the stack.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + Returns a standard interface for operations on a collection,
Does the class "returns a standard interface"?!

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + which is organized according to the principle last in first out, called a `stack`.
Please simplify description according to the recommendations above.

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// An array with the elements of the stack collection.
nit:

also I know this is an array, you can simplify it as:
```suggestion
    /// Contains elements of the stack.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     Adds the element  to the end of the stack collection.
```suggestion
     Adds the element to the end of the stack collection.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
You don't need to mention it. If you click on the method to see the documentation, you will see:

```
...
In the collection `currentMinElements`is filled
...
```

But the client code (developer who uses the code) won't have an access to `currentMinElements`. So you're exposing the implementation detail. This is a bad practice.

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     The last element is removed from the `currentMinElements` collection.
Same note as above: you don't need to mention private interface in the public interface.

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
Please check the rest. Before submitting the changes, you HAVE TO check the grammar. This is not a job of the reviewer!

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     Returns the minimum element in the collection.
```suggestion
     Returns the minimum element in the stack.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
```suggestion
     If the stack is empty, returns `nil`.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     - Returns: The minimum element in the collection.
```suggestion
     - Returns: The minimum element in the stack.
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
You need to write this detail (about returning `nil` and conditions in the "- Returns: " section, not in the summary.

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
Please fix all the rest.

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
```suggestion
     In the collection `currentMinElements` is filled
```

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
I'm trying to translate it:

```
В коллекции currentMinElements заполнена текущим минимальным значением.
```

I do not understand what does that mean :(

2020-09-27 15:52 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Array with minimum elements of collection.
Imagine, some stack is [1,3,5,1,3,1,1].

Doc says:
> `currentMinElements` is an array with minimum elements of collection (stack)

So, `currentMinElements` will contain [1, 1, 1, 1]. Because these are minimum elements. Am I right?

2020-09-27 15:52 UTC, dersim-davaod commented on README.md
> +stack.push(Int)
Really?! You can write such code in Swift?

2020-09-27 15:57 UTC, dersim-davaod commented
Ok, [you said](https://github.com/pingvin1977/ios-school-homeworks/pull/3#discussion_r495418595) that you are familiar with articles about README file. 

Where I can find answers to the following questions:
1. What is the name of repo in the README file?
1. Where is the description? What is the purpose of the repo?
1. Have you tried to use badges?
1. How to install and use your code snippets if that's possible?
1. How to collaborate with you?
1. Who is the author of the code?

2020-09-27 15:59 UTC, dersim-davaod commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
Again. Please do not ignore questions when asked. "Fixed" is a dumb answer.

What was fixed at previous iteration? What you have fixed last time? Why do you think something is fixed?

2020-09-27 16:57 UTC, pingvin1977 commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
Maybe I didn't understand the question. 
Is there an extra line 9 in this code?

2020-09-27 17:01 UTC, pingvin1977 commented on README.md
> +## Usage skack operation
Fixed to stack.

2020-09-27 17:06 UTC, pingvin1977 commented on README.md
> + which are organized according to the principle last in-first out, which is called the <a href="https://en.wikipedia.org/wiki/Stack_(abstract_data_type)">stack</a>.
Corrected to [link](url).

2020-09-27 17:07 UTC, pingvin1977 commented on README.md
> + which are organized according to the principle last in-first out, which is called the <a href="https://en.wikipedia.org/wiki/Stack_(abstract_data_type)">stack</a>.
Fixed.

2020-09-27 17:09 UTC, pingvin1977 commented on README.md
> +The class StackStatistics is designed to implement API-interfaces for basic operations on a list of elements,
Corrected to API.

2020-09-27 17:49 UTC, pingvin1977 commented on README.md
> +Using the class, it is possible to add an element to the end of the stack, remove the last element,
Сhanged "end of the stack" to "end of stack collection" and "the last element" to "the last element of the stack collection".

2020-09-27 19:46 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /// An array with the elements of the stack collection.
Corrected to "сontains elements of the stack".

2020-09-27 20:05 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> + remove an element from the collection and read the last element of the collection.
Corrected.

2020-09-27 20:07 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     func push(_ element: Int) {
Fixed.

2020-09-27 20:18 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     Removes the last element from the stack collection and returns it.
Corrected.

2020-09-27 20:20 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     Removes the last element from the stack collection and returns it.
Corrected to "removes the element that added last from the stack and returns it"

2020-09-27 20:21 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
Corrected.

2020-09-27 20:22 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
Corrected.

2020-09-27 20:22 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
Corrected.

2020-09-27 20:23 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     - Returns: The last element of the collection.
Corrected.

2020-09-27 20:25 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> + Returns a standard interface for operations on a collection,
Corrected "returns" to "provides".

2020-09-28 06:50 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
All fixed.

2020-09-28 06:51 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     Adds the element  to the end of the stack collection.
Fixed.

2020-09-28 07:01 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> + which is organized according to the principle last in first out, called a `stack`.
Corrected.

2020-09-28 07:05 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
Deleted description `currentMinElements`.

2020-09-28 07:06 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     The last element is removed from the `currentMinElements` collection.
Removed.

2020-09-28 07:13 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     Returns the minimum element in the collection.
Fixed.

2020-09-28 07:14 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
Fixed.

2020-09-28 07:14 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     - Returns: The minimum element in the collection.
Fixed.

2020-09-28 07:17 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
Description of `currentMinElements` is deleted.

2020-09-28 07:19 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
Description of `currentMinElements` removed because it is private.

2020-09-28 07:38 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> + which is organized according to the principle last in first out, called a `stack`.
Added to the description "the stack can hold `Int` values only"

2020-09-28 07:43 UTC, pingvin1977 commented on README.md
> +stack.push(Int)
Corrected.

2020-09-28 08:44 UTC, pingvin1977 commented on README.md
> +Using the class, it is possible to add an element to the end of the stack, remove the last element,
Corrected.

2020-09-28 08:52 UTC, pingvin1977 commented on README.md
> +Using the class, it is possible to add an element to the end of the stack, remove the last element,
Сhanged.

2020-09-28 09:00 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     If the collection is empty, return `nil`.
Fixed.

2020-09-28 09:02 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
Description removed.

2020-09-28 09:03 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
Description removed.

2020-09-28 09:17 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     Adds the element  to the end of the stack collection.
Corrected.

2020-09-28 11:33 UTC, dersim-davaod commented on README.md
> +stackStatistic.push(Int) // Adds an element on the top of the stack.
No, my comment is related to line 10, as it is stated.

The initial question about why you think the specific line of code above should be in "Usage" section.
You answered just "Fixed".
I couldn't see any changes, so I've asked you "What was fixed?".
You said just "Fixed." one more time.

If I ask question, I want a specific answer. Here you have ignored my questions 2 times and have provided me with answers that didn't give any useful information.

The reason why I'm asking questions is to force you to analyze changes and find the issue. Meanwhile you can argue your decision.

Does that make sense?

2020-09-28 18:45 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     The last element is removed from the `currentMinElements` collection.
Removed.

2020-09-28 18:50 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     In the collection `currentMinElements`is filled
I don't know how to describe this array.

2020-09-29 06:39 UTC, dersim-davaod commented on README.md
> +## Usage skack operation
No, it's not

2020-09-29 06:40 UTC, dersim-davaod commented on README.md
> + which are organized according to the principle last in-first out, which is called the <a href="https://en.wikipedia.org/wiki/Stack_(abstract_data_type)">stack</a>.
I still see HTML tags.

2020-09-29 06:40 UTC, dersim-davaod commented on README.md
> + which are organized according to the principle last in-first out, which is called the <a href="https://en.wikipedia.org/wiki/Stack_(abstract_data_type)">stack</a>.
seems it's not fixed.

2020-09-29 06:40 UTC, dersim-davaod commented on README.md
> +The class StackStatistics is designed to implement API-interfaces for basic operations on a list of elements,
Seems, it's not fixed.

2020-09-29 06:40 UTC, dersim-davaod commented on README.md
> +# Stack Statistics
Before re-requesting review, make sure you have addressed all previous comments.

2020-09-29 06:41 UTC, dersim-davaod commented on README.md
> +# Stack Statistics
Before re-requesting review, make sure you have addressed all previous comments.

2020-09-29 06:41 UTC, dersim-davaod commented on README.md
> +The class StackStatistics is designed to implement API-interfaces for basic operations on a list of elements,
Before re-requesting review, make sure you have addressed all previous comments.

2020-09-29 06:42 UTC, dersim-davaod commented on README.md
> +Using the class, it is possible to add an element to the end of the stack, remove the last element,
Seems, it's not. Please double check this before submitting. Also please remind me to discuss this case in class.

2020-09-29 06:42 UTC, dersim-davaod commented on README.md
> +Using the class, it is possible to add an element to the end of the stack, remove the last element,
It's not changed.

2020-09-29 06:44 UTC, dersim-davaod requested changes
Basically, I see a lot of changes you promised to do, but I couldn't see them. Double check that and address open conversations.

Also I thought we agreed to move doc-related changes into a separate PR, didn't we?

Please remind me to discuss this in class.

2020-10-01 16:37 UTC, dersim-davaod requested changes
We agreed that changes should contain only code.
I see update README.md file. Moreover you didn't address comments related to README.md.

2020-10-02 05:31 UTC, dersim-davaod approved these changes
Good job!

2020-10-03 08:50 UTC, merged