Added documentation
pingvin1977/ios-school-homeworks pull request #4
Opened 2020-10-02 10:23 UTC by pingvin1977

2020-10-02 10:56 UTC, dersim-davaod requested changes

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +/**
Leave a blank line after `// MARK:`

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +//MARK: - Stack
```suggestion
//  MARK: - Stack
```

Check the rest please

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + Provides a standard interface for on a collection,
> for on a collection

What does that mean?

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + wich is organized according to the principle "last in, first out", called a
```suggestion
 which is organized according to the principle "last in, first out", called a
```

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
Leave a blank after the last declaration (property/function).
Please check the rest.

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + wich is organized according to the principle "last in, first out", called a
Why you didn't use grammarly service?

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     - Complexity: 0(1)
```suggestion
     - Complexity: O(1)
```

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     - Complexity: 0(1)
Fix the rest.

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     - Complexity: 0(1)
```suggestion
     - Complexity: O(1)
```

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    ///
?

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
Why you're copy-pasting this docs? Is that required?

2020-10-02 10:56 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
Why you're copy-pasting this docs? Is that required?

2020-10-02 11:39 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +/**
Added lines.

2020-10-02 11:39 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +//MARK: - Stack
Fixed.

2020-10-02 11:45 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> + wich is organized according to the principle "last in, first out", called a
Grammarly service does not check grammar in Xcode.

2020-10-02 11:47 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     - Complexity: 0(1)
Fixed.

2020-10-02 11:48 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +     - Complexity: 0(1)
Fixed.

2020-10-02 11:58 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
Fixed.

2020-10-02 12:04 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> + Provides a standard interface for on a collection,
Sorry, i missed a word "operation". Fixed.

2020-10-02 12:09 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
I didn't leave blank lines. Fixed.

2020-10-02 12:09 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
I didn't leave blank lines. Fixed.

2020-10-02 12:37 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    ///
Added description.

2020-10-02 12:37 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> + wich is organized according to the principle "last in, first out", called a
Fixed.

2020-10-02 15:02 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +//MARK: - Stack
Sorry, I did a typo there.
I meant to have only one space after `//` characters.

Please fix it.

2020-10-02 15:04 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + wich is organized according to the principle "last in, first out", called a
Sure, it doesn't! There's no code editor that does this.
You can copy-paste some text and check the grammar/spelling. Then copy text back into Xcode.

2020-10-02 15:05 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + wich is organized according to the principle "last in, first out", called a
My point as we discussed - this is your job to make sure grammar is ok before submitting PR.

2020-10-02 15:06 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
No it doesn't. Line 22, for example:
```swift
    func push(_ element: Int) {
        stackElements.append(element)		    
        stackElements.append(element)	    
    }
    /**
    Removes the element that added last from the stack and return it.

```

2020-10-02 15:08 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
I mean why you have copied the same docs from `Stack` class? Is that required?

2020-10-02 15:10 UTC, dersim-davaod requested changes

2020-10-02 15:10 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// The last added value is the minimum value on the stack.
> Sorted stack from maximum to minimum.

So if our stack is

`[1,5,7,3,5,9]`

, then `currentMinElements` will be

`[9,7,5,5,3,1]`

Am I right?

2020-10-02 16:58 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +//MARK: - Stack
Fixed.

2020-10-02 17:00 UTC, pingvin1977 commented on iOS-School-02_stack.playground/Contents.swift
> +    /**
Fixed.

2020-10-03 15:40 UTC, dersim-davaod requested changes
Before re-requesting review, address unresolved/unanswered issues!

Plus consider improvements below.

2020-10-03 15:40 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Contains of minimal elements.
1. Check grammar!

2020-10-03 15:40 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Contains of minimal elements.
> Contains of minimal elements.

So, if our stack is

[1,5,7,3,5,1,9]

, then currentMinElements will be

[1,1] as this is min elements.

Am I right?

2020-10-07 07:14 UTC, dersim-davaod requested changes
Consider improvements below.

Also please rename PR. E.g.: "HW#2: add documentation for Stack/StackStatistics classes".

2020-10-07 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> + You can add, remove an element from the stack and peek the element that added last.
I would remove this line.

2020-10-07 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +     - Parameter element; An element to add on the stack.
```suggestion
     - Parameter element: An element to add on the stack.
```

2020-10-07 07:14 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Collection of elements.
Is that random collection of elements?

Could you please describe what `currentMinElements` stores in Russian?

2020-10-16 14:26 UTC, dersim-davaod requested changes

2020-10-16 14:26 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Collection of current min element.
Could you please translate this into Russian?
Will that be `коллекция текущего минимального элемента`?

2020-10-16 14:26 UTC, dersim-davaod commented on iOS-School-02_stack.playground/Contents.swift
> +    /// Collection of current min element.
I would write something like:
```swift
/**
 Contains current min elements. Each time a new element is added into the stack, new current min element is added into the `currentMinElements ` collection. As soon as some element is removed from the stack, latest element is removed from the `currentMinElements` collection. Thus the latest element points to the min element in the stack at the current moment.
 */
```

Does that make sense?

2020-10-20 08:39 UTC, dersim-davaod approved these changes
LGTM

2020-10-20 08:47 UTC, merged