Added items Description, Installation, Autors and License.
pingvin1977/ios-school-homeworks pull request #5
Opened 2020-10-04 15:39 UTC by pingvin1977

2020-10-07 07:11 UTC, dersim-davaod requested changes
Consider the changes below.

Also please give your PR more descriptive name. E.g.:
Update README file: add Description, Installation, Authors and License sections.

Also there's a typo in the name of the PR: Autors -> Authors.

2020-10-07 07:11 UTC, dersim-davaod commented on README.md
> +[![CocoaPods Platforms](https://img.shields.io/cocoapods/p/m)](https://img.shields.io/cocoapods/p/m?color=gree)
👍

2020-10-07 07:11 UTC, dersim-davaod commented on README.md
> +This repository contains practical homework solutions for learning the program language `swift`
I didn't understand the sentence:

> for learning the program language `swift` school "iOS CocoaHeads August 2020"

2020-10-07 07:11 UTC, dersim-davaod commented on README.md
> +school "iOS CocoaHeads August 2020". Homeworks is divided into directories.
```suggestion
school "iOS CocoaHeads August 2020". Each homework is in the separate directory.
```

2020-10-07 07:11 UTC, dersim-davaod commented on README.md
> +You need [XCode](apps.apple.com/us/app/xcode/id497799835?mt=12) application to run jobs.
which jobs?

2020-10-07 07:11 UTC, dersim-davaod commented on README.md
> +You need [XCode](apps.apple.com/us/app/xcode/id497799835?mt=12) application to run jobs.
Please remember how to write IDE's name: not `XCode`, but `Xcode`.

2020-10-07 07:11 UTC, dersim-davaod commented on README.md
> +## Autors
```suggestion
## Authors
```

2020-10-07 07:11 UTC, dersim-davaod commented on README.md
> +Thanks to my mentor [Dersim Davaod](github.com/dersim-davaod) who contributed a lot to this project and the volunteer
Please don't mention me :)
Also you don't have to mention ByChange (but you can if you want).

In the simplest form just leave it as:
```
## Authors
[Yury Gudyma](github-nickname)
```

as you're a main author.

2020-10-07 07:11 UTC, dersim-davaod commented on README.md
> +
```suggestion
```

2020-10-07 20:02 UTC, pingvin1977 commented on README.md
> +school "iOS CocoaHeads August 2020". Homeworks is divided into directories.
Fixed.

2020-10-07 20:02 UTC, pingvin1977 commented on README.md
> +You need [XCode](apps.apple.com/us/app/xcode/id497799835?mt=12) application to run jobs.
Fixed.

2020-10-07 20:05 UTC, pingvin1977 commented on README.md
> +## Autors
Fixed.

2020-10-07 20:07 UTC, pingvin1977 commented on README.md
> +Thanks to my mentor [Dersim Davaod](github.com/dersim-davaod) who contributed a lot to this project and the volunteer
Changed the author.

2020-10-07 20:08 UTC, pingvin1977 commented on README.md
> +
Fixed.

2020-10-07 20:32 UTC, pingvin1977 commented on README.md
> +You need [XCode](apps.apple.com/us/app/xcode/id497799835?mt=12) application to run jobs.
Jobs corrected to works

2020-10-08 08:01 UTC, pingvin1977 commented on README.md
> +This repository contains practical homework solutions for learning the program language `swift`
Rewrote description.

2020-10-16 14:30 UTC, dersim-davaod requested changes

2020-10-16 14:30 UTC, dersim-davaod commented on README.md
> +at the online school "iOS CocoaHeads August 2020". Each homework is in the separate directorys.
```suggestion
at the online school "iOS CocoaHeads August 2020". Each homework is in the separate directory.
```

2020-10-16 14:30 UTC, dersim-davaod commented on README.md
> +You need [Xcode](apps.apple.com/us/app/xcode/id497799835?mt=12) application to run works.
> _to run works_

Which works?

2020-10-16 14:30 UTC, dersim-davaod commented on README.md
> +You need [Xcode](apps.apple.com/us/app/xcode/id497799835?mt=12) application to run works.
```suggestion
The code is written in Xcode, so you need [Xcode](apps.apple.com/us/app/xcode/id497799835?mt=12) and CLT to run playgrounds/projects.
```

2020-10-16 14:30 UTC, dersim-davaod commented on README.md
> +You need [Xcode](apps.apple.com/us/app/xcode/id497799835?mt=12) application to run works.
Also: which version of Xcode do I need? Is that ok to use Xcode 10?

2020-10-16 16:40 UTC, pingvin1977 commented on README.md
> +at the online school "iOS CocoaHeads August 2020". Each homework is in the separate directorys.
Fixed.

2020-10-16 17:04 UTC, pingvin1977 commented on README.md
> +You need [Xcode](apps.apple.com/us/app/xcode/id497799835?mt=12) application to run works.
Added the Xcode version to the description and rewrote the installation.

2020-10-20 08:38 UTC, dersim-davaod approved these changes
LGTM

2020-10-20 08:45 UTC, merged